// This file is auto-generated by scripts/generate-native-push-config.mjs.
// Re-run `npm run build` or `npm run native:refresh` after changing native push files.

export const NATIVE_PUSH_CONFIG = {
  ios: {
    enabled: true,
  },
  android: {
    enabled: true,
  },
} as const;
